# This rule is not used by the project axonops-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to alerts.axonops.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: axonops-operator
    app.kubernetes.io/managed-by: kustomize
  name: alerts-axonopshealthcheckshell-viewer-role
rules:
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopshealthcheckshells
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopshealthcheckshells/status
  verbs:
  - get
