# This rule is not used by the project axonops-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.axonops.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: axonops-operator
    app.kubernetes.io/managed-by: kustomize
  name: axonopsplatform-admin-role
rules:
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsplatforms
  verbs:
  - '*'
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsplatforms/status
  verbs:
  - get
