---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsalertroutes
  - axonopshealthcheckhttps
  - axonopshealthcheckshells
  - axonopshealthchecktcps
  - axonopslogalerts
  - axonopsmetricalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsalertroutes/finalizers
  - axonopshealthcheckhttps/finalizers
  - axonopshealthcheckshells/finalizers
  - axonopshealthchecktcps/finalizers
  - axonopslogalerts/finalizers
  - axonopsmetricalerts/finalizers
  verbs:
  - update
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsalertroutes/status
  - axonopshealthcheckhttps/status
  - axonopshealthcheckshells/status
  - axonopshealthchecktcps/status
  - axonopslogalerts/status
  - axonopsmetricalerts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers/finalizers
  verbs:
  - update
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers/status
  verbs:
  - get
  - patch
  - update
