//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAdaptiveRepair) DeepCopyInto(out *AxonOpsAdaptiveRepair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAdaptiveRepair.
func (in *AxonOpsAdaptiveRepair) DeepCopy() *AxonOpsAdaptiveRepair {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAdaptiveRepair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAdaptiveRepair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAdaptiveRepairList) DeepCopyInto(out *AxonOpsAdaptiveRepairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsAdaptiveRepair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAdaptiveRepairList.
func (in *AxonOpsAdaptiveRepairList) DeepCopy() *AxonOpsAdaptiveRepairList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAdaptiveRepairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAdaptiveRepairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAdaptiveRepairSpec) DeepCopyInto(out *AxonOpsAdaptiveRepairSpec) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.GcGraceThreshold != nil {
		in, out := &in.GcGraceThreshold, &out.GcGraceThreshold
		*out = new(int64)
		**out = **in
	}
	if in.TableParallelism != nil {
		in, out := &in.TableParallelism, &out.TableParallelism
		*out = new(int32)
		**out = **in
	}
	if in.ExcludedTables != nil {
		in, out := &in.ExcludedTables, &out.ExcludedTables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FilterTWCSTables != nil {
		in, out := &in.FilterTWCSTables, &out.FilterTWCSTables
		*out = new(bool)
		**out = **in
	}
	if in.SegmentRetries != nil {
		in, out := &in.SegmentRetries, &out.SegmentRetries
		*out = new(int32)
		**out = **in
	}
	if in.SegmentTargetSizeMB != nil {
		in, out := &in.SegmentTargetSizeMB, &out.SegmentTargetSizeMB
		*out = new(int32)
		**out = **in
	}
	if in.MaxSegmentsPerTable != nil {
		in, out := &in.MaxSegmentsPerTable, &out.MaxSegmentsPerTable
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAdaptiveRepairSpec.
func (in *AxonOpsAdaptiveRepairSpec) DeepCopy() *AxonOpsAdaptiveRepairSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAdaptiveRepairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAdaptiveRepairStatus) DeepCopyInto(out *AxonOpsAdaptiveRepairStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAdaptiveRepairStatus.
func (in *AxonOpsAdaptiveRepairStatus) DeepCopy() *AxonOpsAdaptiveRepairStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAdaptiveRepairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertEndpoint) DeepCopyInto(out *AxonOpsAlertEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertEndpoint.
func (in *AxonOpsAlertEndpoint) DeepCopy() *AxonOpsAlertEndpoint {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAlertEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertEndpointList) DeepCopyInto(out *AxonOpsAlertEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsAlertEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertEndpointList.
func (in *AxonOpsAlertEndpointList) DeepCopy() *AxonOpsAlertEndpointList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAlertEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertEndpointSpec) DeepCopyInto(out *AxonOpsAlertEndpointSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(PagerDutyEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OpsGenie != nil {
		in, out := &in.OpsGenie, &out.OpsGenie
		*out = new(OpsGenieEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceNow != nil {
		in, out := &in.ServiceNow, &out.ServiceNow
		*out = new(ServiceNowEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MicrosoftTeams != nil {
		in, out := &in.MicrosoftTeams, &out.MicrosoftTeams
		*out = new(MicrosoftTeamsEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertEndpointSpec.
func (in *AxonOpsAlertEndpointSpec) DeepCopy() *AxonOpsAlertEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertEndpointStatus) DeepCopyInto(out *AxonOpsAlertEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertEndpointStatus.
func (in *AxonOpsAlertEndpointStatus) DeepCopy() *AxonOpsAlertEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertRoute) DeepCopyInto(out *AxonOpsAlertRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertRoute.
func (in *AxonOpsAlertRoute) DeepCopy() *AxonOpsAlertRoute {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAlertRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertRouteList) DeepCopyInto(out *AxonOpsAlertRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsAlertRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertRouteList.
func (in *AxonOpsAlertRouteList) DeepCopy() *AxonOpsAlertRouteList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsAlertRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertRouteSpec) DeepCopyInto(out *AxonOpsAlertRouteSpec) {
	*out = *in
	if in.EnableOverride != nil {
		in, out := &in.EnableOverride, &out.EnableOverride
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertRouteSpec.
func (in *AxonOpsAlertRouteSpec) DeepCopy() *AxonOpsAlertRouteSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsAlertRouteStatus) DeepCopyInto(out *AxonOpsAlertRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsAlertRouteStatus.
func (in *AxonOpsAlertRouteStatus) DeepCopy() *AxonOpsAlertRouteStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsAlertRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsCommitlogArchive) DeepCopyInto(out *AxonOpsCommitlogArchive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsCommitlogArchive.
func (in *AxonOpsCommitlogArchive) DeepCopy() *AxonOpsCommitlogArchive {
	if in == nil {
		return nil
	}
	out := new(AxonOpsCommitlogArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsCommitlogArchive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsCommitlogArchiveList) DeepCopyInto(out *AxonOpsCommitlogArchiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsCommitlogArchive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsCommitlogArchiveList.
func (in *AxonOpsCommitlogArchiveList) DeepCopy() *AxonOpsCommitlogArchiveList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsCommitlogArchiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsCommitlogArchiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsCommitlogArchiveSpec) DeepCopyInto(out *AxonOpsCommitlogArchiveSpec) {
	*out = *in
	if in.Transfers != nil {
		in, out := &in.Transfers, &out.Transfers
		*out = new(int32)
		**out = **in
	}
	if in.Datacenters != nil {
		in, out := &in.Datacenters, &out.Datacenters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(CommitlogS3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(CommitlogSFTPConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsCommitlogArchiveSpec.
func (in *AxonOpsCommitlogArchiveSpec) DeepCopy() *AxonOpsCommitlogArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsCommitlogArchiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsCommitlogArchiveStatus) DeepCopyInto(out *AxonOpsCommitlogArchiveStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsCommitlogArchiveStatus.
func (in *AxonOpsCommitlogArchiveStatus) DeepCopy() *AxonOpsCommitlogArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsCommitlogArchiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsDashboardTemplate) DeepCopyInto(out *AxonOpsDashboardTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsDashboardTemplate.
func (in *AxonOpsDashboardTemplate) DeepCopy() *AxonOpsDashboardTemplate {
	if in == nil {
		return nil
	}
	out := new(AxonOpsDashboardTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsDashboardTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsDashboardTemplateList) DeepCopyInto(out *AxonOpsDashboardTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsDashboardTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsDashboardTemplateList.
func (in *AxonOpsDashboardTemplateList) DeepCopy() *AxonOpsDashboardTemplateList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsDashboardTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsDashboardTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsDashboardTemplateSpec) DeepCopyInto(out *AxonOpsDashboardTemplateSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsDashboardTemplateSpec.
func (in *AxonOpsDashboardTemplateSpec) DeepCopy() *AxonOpsDashboardTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsDashboardTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsDashboardTemplateStatus) DeepCopyInto(out *AxonOpsDashboardTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsDashboardTemplateStatus.
func (in *AxonOpsDashboardTemplateStatus) DeepCopy() *AxonOpsDashboardTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsDashboardTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckHTTP) DeepCopyInto(out *AxonOpsHealthcheckHTTP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckHTTP.
func (in *AxonOpsHealthcheckHTTP) DeepCopy() *AxonOpsHealthcheckHTTP {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckHTTP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckHTTPList) DeepCopyInto(out *AxonOpsHealthcheckHTTPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsHealthcheckHTTP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckHTTPList.
func (in *AxonOpsHealthcheckHTTPList) DeepCopy() *AxonOpsHealthcheckHTTPList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckHTTPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckHTTPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckHTTPSpec) DeepCopyInto(out *AxonOpsHealthcheckHTTPSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SupportedAgentTypes != nil {
		in, out := &in.SupportedAgentTypes, &out.SupportedAgentTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckHTTPSpec.
func (in *AxonOpsHealthcheckHTTPSpec) DeepCopy() *AxonOpsHealthcheckHTTPSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckHTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckHTTPStatus) DeepCopyInto(out *AxonOpsHealthcheckHTTPStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckHTTPStatus.
func (in *AxonOpsHealthcheckHTTPStatus) DeepCopy() *AxonOpsHealthcheckHTTPStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckHTTPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckShell) DeepCopyInto(out *AxonOpsHealthcheckShell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckShell.
func (in *AxonOpsHealthcheckShell) DeepCopy() *AxonOpsHealthcheckShell {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckShell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckShell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckShellList) DeepCopyInto(out *AxonOpsHealthcheckShellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsHealthcheckShell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckShellList.
func (in *AxonOpsHealthcheckShellList) DeepCopy() *AxonOpsHealthcheckShellList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckShellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckShellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckShellSpec) DeepCopyInto(out *AxonOpsHealthcheckShellSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckShellSpec.
func (in *AxonOpsHealthcheckShellSpec) DeepCopy() *AxonOpsHealthcheckShellSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckShellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckShellStatus) DeepCopyInto(out *AxonOpsHealthcheckShellStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckShellStatus.
func (in *AxonOpsHealthcheckShellStatus) DeepCopy() *AxonOpsHealthcheckShellStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckShellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckTCP) DeepCopyInto(out *AxonOpsHealthcheckTCP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckTCP.
func (in *AxonOpsHealthcheckTCP) DeepCopy() *AxonOpsHealthcheckTCP {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckTCP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckTCPList) DeepCopyInto(out *AxonOpsHealthcheckTCPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsHealthcheckTCP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckTCPList.
func (in *AxonOpsHealthcheckTCPList) DeepCopy() *AxonOpsHealthcheckTCPList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckTCPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsHealthcheckTCPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckTCPSpec) DeepCopyInto(out *AxonOpsHealthcheckTCPSpec) {
	*out = *in
	if in.SupportedAgentTypes != nil {
		in, out := &in.SupportedAgentTypes, &out.SupportedAgentTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckTCPSpec.
func (in *AxonOpsHealthcheckTCPSpec) DeepCopy() *AxonOpsHealthcheckTCPSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckTCPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsHealthcheckTCPStatus) DeepCopyInto(out *AxonOpsHealthcheckTCPStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsHealthcheckTCPStatus.
func (in *AxonOpsHealthcheckTCPStatus) DeepCopy() *AxonOpsHealthcheckTCPStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsHealthcheckTCPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlert) DeepCopyInto(out *AxonOpsLogAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlert.
func (in *AxonOpsLogAlert) DeepCopy() *AxonOpsLogAlert {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertList) DeepCopyInto(out *AxonOpsLogAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsLogAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertList.
func (in *AxonOpsLogAlertList) DeepCopy() *AxonOpsLogAlertList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertSpec) DeepCopyInto(out *AxonOpsLogAlertSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(LogAlertFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(LogAlertAnnotations)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = new(LogAlertIntegration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertSpec.
func (in *AxonOpsLogAlertSpec) DeepCopy() *AxonOpsLogAlertSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertStatus) DeepCopyInto(out *AxonOpsLogAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertStatus.
func (in *AxonOpsLogAlertStatus) DeepCopy() *AxonOpsLogAlertStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogCollector) DeepCopyInto(out *AxonOpsLogCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogCollector.
func (in *AxonOpsLogCollector) DeepCopy() *AxonOpsLogCollector {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogCollectorList) DeepCopyInto(out *AxonOpsLogCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsLogCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogCollectorList.
func (in *AxonOpsLogCollectorList) DeepCopy() *AxonOpsLogCollectorList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogCollectorSpec) DeepCopyInto(out *AxonOpsLogCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogCollectorSpec.
func (in *AxonOpsLogCollectorSpec) DeepCopy() *AxonOpsLogCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogCollectorStatus) DeepCopyInto(out *AxonOpsLogCollectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogCollectorStatus.
func (in *AxonOpsLogCollectorStatus) DeepCopy() *AxonOpsLogCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlert) DeepCopyInto(out *AxonOpsMetricAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlert.
func (in *AxonOpsMetricAlert) DeepCopy() *AxonOpsMetricAlert {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsMetricAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertList) DeepCopyInto(out *AxonOpsMetricAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsMetricAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertList.
func (in *AxonOpsMetricAlertList) DeepCopy() *AxonOpsMetricAlertList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsMetricAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertSpec) DeepCopyInto(out *AxonOpsMetricAlertSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(MetricAlertAnnotations)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = new(MetricAlertIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(MetricAlertFilters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertSpec.
func (in *AxonOpsMetricAlertSpec) DeepCopy() *AxonOpsMetricAlertSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertStatus) DeepCopyInto(out *AxonOpsMetricAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertStatus.
func (in *AxonOpsMetricAlertStatus) DeepCopy() *AxonOpsMetricAlertStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsScheduledRepair) DeepCopyInto(out *AxonOpsScheduledRepair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsScheduledRepair.
func (in *AxonOpsScheduledRepair) DeepCopy() *AxonOpsScheduledRepair {
	if in == nil {
		return nil
	}
	out := new(AxonOpsScheduledRepair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsScheduledRepair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsScheduledRepairList) DeepCopyInto(out *AxonOpsScheduledRepairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsScheduledRepair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsScheduledRepairList.
func (in *AxonOpsScheduledRepairList) DeepCopy() *AxonOpsScheduledRepairList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsScheduledRepairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsScheduledRepairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsScheduledRepairSpec) DeepCopyInto(out *AxonOpsScheduledRepairSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlacklistedTables != nil {
		in, out := &in.BlacklistedTables, &out.BlacklistedTables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SpecificDataCenters != nil {
		in, out := &in.SpecificDataCenters, &out.SpecificDataCenters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsScheduledRepairSpec.
func (in *AxonOpsScheduledRepairSpec) DeepCopy() *AxonOpsScheduledRepairSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsScheduledRepairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsScheduledRepairStatus) DeepCopyInto(out *AxonOpsScheduledRepairStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsScheduledRepairStatus.
func (in *AxonOpsScheduledRepairStatus) DeepCopy() *AxonOpsScheduledRepairStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsScheduledRepairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsSilenceWindow) DeepCopyInto(out *AxonOpsSilenceWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsSilenceWindow.
func (in *AxonOpsSilenceWindow) DeepCopy() *AxonOpsSilenceWindow {
	if in == nil {
		return nil
	}
	out := new(AxonOpsSilenceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsSilenceWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsSilenceWindowList) DeepCopyInto(out *AxonOpsSilenceWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsSilenceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsSilenceWindowList.
func (in *AxonOpsSilenceWindowList) DeepCopy() *AxonOpsSilenceWindowList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsSilenceWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsSilenceWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsSilenceWindowSpec) DeepCopyInto(out *AxonOpsSilenceWindowSpec) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Datacenters != nil {
		in, out := &in.Datacenters, &out.Datacenters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsSilenceWindowSpec.
func (in *AxonOpsSilenceWindowSpec) DeepCopy() *AxonOpsSilenceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsSilenceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsSilenceWindowStatus) DeepCopyInto(out *AxonOpsSilenceWindowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsSilenceWindowStatus.
func (in *AxonOpsSilenceWindowStatus) DeepCopy() *AxonOpsSilenceWindowStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsSilenceWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitlogS3Config) DeepCopyInto(out *CommitlogS3Config) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(CommitlogSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitlogS3Config.
func (in *CommitlogS3Config) DeepCopy() *CommitlogS3Config {
	if in == nil {
		return nil
	}
	out := new(CommitlogS3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitlogSFTPConfig) DeepCopyInto(out *CommitlogSFTPConfig) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(CommitlogSFTPCredentialsRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitlogSFTPConfig.
func (in *CommitlogSFTPConfig) DeepCopy() *CommitlogSFTPConfig {
	if in == nil {
		return nil
	}
	out := new(CommitlogSFTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitlogSFTPCredentialsRef) DeepCopyInto(out *CommitlogSFTPCredentialsRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitlogSFTPCredentialsRef.
func (in *CommitlogSFTPCredentialsRef) DeepCopy() *CommitlogSFTPCredentialsRef {
	if in == nil {
		return nil
	}
	out := new(CommitlogSFTPCredentialsRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitlogSecretRef) DeepCopyInto(out *CommitlogSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitlogSecretRef.
func (in *CommitlogSecretRef) DeepCopy() *CommitlogSecretRef {
	if in == nil {
		return nil
	}
	out := new(CommitlogSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardConfigMapRef) DeepCopyInto(out *DashboardConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardConfigMapRef.
func (in *DashboardConfigMapRef) DeepCopy() *DashboardConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(DashboardConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardInline) DeepCopyInto(out *DashboardInline) {
	*out = *in
	in.Dashboard.DeepCopyInto(&out.Dashboard)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardInline.
func (in *DashboardInline) DeepCopy() *DashboardInline {
	if in == nil {
		return nil
	}
	out := new(DashboardInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSource) DeepCopyInto(out *DashboardSource) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(DashboardInline)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(DashboardConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSource.
func (in *DashboardSource) DeepCopy() *DashboardSource {
	if in == nil {
		return nil
	}
	out := new(DashboardSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAlertAnnotations) DeepCopyInto(out *LogAlertAnnotations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAlertAnnotations.
func (in *LogAlertAnnotations) DeepCopy() *LogAlertAnnotations {
	if in == nil {
		return nil
	}
	out := new(LogAlertAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAlertFilters) DeepCopyInto(out *LogAlertFilters) {
	*out = *in
	if in.DataCenter != nil {
		in, out := &in.DataCenter, &out.DataCenter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rack != nil {
		in, out := &in.Rack, &out.Rack
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostID != nil {
		in, out := &in.HostID, &out.HostID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAlertFilters.
func (in *LogAlertFilters) DeepCopy() *LogAlertFilters {
	if in == nil {
		return nil
	}
	out := new(LogAlertFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAlertIntegration) DeepCopyInto(out *LogAlertIntegration) {
	*out = *in
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAlertIntegration.
func (in *LogAlertIntegration) DeepCopy() *LogAlertIntegration {
	if in == nil {
		return nil
	}
	out := new(LogAlertIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertAnnotations) DeepCopyInto(out *MetricAlertAnnotations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertAnnotations.
func (in *MetricAlertAnnotations) DeepCopy() *MetricAlertAnnotations {
	if in == nil {
		return nil
	}
	out := new(MetricAlertAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertFilters) DeepCopyInto(out *MetricAlertFilters) {
	*out = *in
	if in.DataCenter != nil {
		in, out := &in.DataCenter, &out.DataCenter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rack != nil {
		in, out := &in.Rack, &out.Rack
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostID != nil {
		in, out := &in.HostID, &out.HostID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keyspace != nil {
		in, out := &in.Keyspace, &out.Keyspace
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Consistency != nil {
		in, out := &in.Consistency, &out.Consistency
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertFilters.
func (in *MetricAlertFilters) DeepCopy() *MetricAlertFilters {
	if in == nil {
		return nil
	}
	out := new(MetricAlertFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertIntegration) DeepCopyInto(out *MetricAlertIntegration) {
	*out = *in
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertIntegration.
func (in *MetricAlertIntegration) DeepCopy() *MetricAlertIntegration {
	if in == nil {
		return nil
	}
	out := new(MetricAlertIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrosoftTeamsEndpointConfig) DeepCopyInto(out *MicrosoftTeamsEndpointConfig) {
	*out = *in
	if in.WebHookURLSecretRef != nil {
		in, out := &in.WebHookURLSecretRef, &out.WebHookURLSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrosoftTeamsEndpointConfig.
func (in *MicrosoftTeamsEndpointConfig) DeepCopy() *MicrosoftTeamsEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MicrosoftTeamsEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsGenieEndpointConfig) DeepCopyInto(out *OpsGenieEndpointConfig) {
	*out = *in
	if in.OpsGenieKeySecretRef != nil {
		in, out := &in.OpsGenieKeySecretRef, &out.OpsGenieKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsGenieEndpointConfig.
func (in *OpsGenieEndpointConfig) DeepCopy() *OpsGenieEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(OpsGenieEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerDutyEndpointConfig) DeepCopyInto(out *PagerDutyEndpointConfig) {
	*out = *in
	if in.IntegrationKeySecretRef != nil {
		in, out := &in.IntegrationKeySecretRef, &out.IntegrationKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerDutyEndpointConfig.
func (in *PagerDutyEndpointConfig) DeepCopy() *PagerDutyEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(PagerDutyEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNowEndpointConfig) DeepCopyInto(out *ServiceNowEndpointConfig) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNowEndpointConfig.
func (in *ServiceNowEndpointConfig) DeepCopy() *ServiceNowEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceNowEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackEndpointConfig) DeepCopyInto(out *SlackEndpointConfig) {
	*out = *in
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackEndpointConfig.
func (in *SlackEndpointConfig) DeepCopy() *SlackEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(SlackEndpointConfig)
	in.DeepCopyInto(out)
	return out
}
