//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlert) DeepCopyInto(out *AxonOpsLogAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlert.
func (in *AxonOpsLogAlert) DeepCopy() *AxonOpsLogAlert {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertList) DeepCopyInto(out *AxonOpsLogAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsLogAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertList.
func (in *AxonOpsLogAlertList) DeepCopy() *AxonOpsLogAlertList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsLogAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertSpec) DeepCopyInto(out *AxonOpsLogAlertSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(LogAlertAnnotations)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = make([]LogAlertIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertSpec.
func (in *AxonOpsLogAlertSpec) DeepCopy() *AxonOpsLogAlertSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsLogAlertStatus) DeepCopyInto(out *AxonOpsLogAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsLogAlertStatus.
func (in *AxonOpsLogAlertStatus) DeepCopy() *AxonOpsLogAlertStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsLogAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlert) DeepCopyInto(out *AxonOpsMetricAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlert.
func (in *AxonOpsMetricAlert) DeepCopy() *AxonOpsMetricAlert {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsMetricAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertList) DeepCopyInto(out *AxonOpsMetricAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsMetricAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertList.
func (in *AxonOpsMetricAlertList) DeepCopy() *AxonOpsMetricAlertList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsMetricAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertSpec) DeepCopyInto(out *AxonOpsMetricAlertSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(MetricAlertAnnotations)
		**out = **in
	}
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = make([]MetricAlertIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(MetricAlertFilters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertSpec.
func (in *AxonOpsMetricAlertSpec) DeepCopy() *AxonOpsMetricAlertSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsMetricAlertStatus) DeepCopyInto(out *AxonOpsMetricAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsMetricAlertStatus.
func (in *AxonOpsMetricAlertStatus) DeepCopy() *AxonOpsMetricAlertStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsMetricAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAlertAnnotations) DeepCopyInto(out *LogAlertAnnotations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAlertAnnotations.
func (in *LogAlertAnnotations) DeepCopy() *LogAlertAnnotations {
	if in == nil {
		return nil
	}
	out := new(LogAlertAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAlertIntegration) DeepCopyInto(out *LogAlertIntegration) {
	*out = *in
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAlertIntegration.
func (in *LogAlertIntegration) DeepCopy() *LogAlertIntegration {
	if in == nil {
		return nil
	}
	out := new(LogAlertIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertAnnotations) DeepCopyInto(out *MetricAlertAnnotations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertAnnotations.
func (in *MetricAlertAnnotations) DeepCopy() *MetricAlertAnnotations {
	if in == nil {
		return nil
	}
	out := new(MetricAlertAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertFilters) DeepCopyInto(out *MetricAlertFilters) {
	*out = *in
	if in.DataCenter != nil {
		in, out := &in.DataCenter, &out.DataCenter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rack != nil {
		in, out := &in.Rack, &out.Rack
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostID != nil {
		in, out := &in.HostID, &out.HostID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Keyspace != nil {
		in, out := &in.Keyspace, &out.Keyspace
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Consistency != nil {
		in, out := &in.Consistency, &out.Consistency
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertFilters.
func (in *MetricAlertFilters) DeepCopy() *MetricAlertFilters {
	if in == nil {
		return nil
	}
	out := new(MetricAlertFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlertIntegration) DeepCopyInto(out *MetricAlertIntegration) {
	*out = *in
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlertIntegration.
func (in *MetricAlertIntegration) DeepCopy() *MetricAlertIntegration {
	if in == nil {
		return nil
	}
	out := new(MetricAlertIntegration)
	in.DeepCopyInto(out)
	return out
}
