## Append samples of your project ##
resources:
- core_v1alpha1_axonopsserver.yaml
- alerts_v1alpha1_axonopsmetricalert.yaml
- alerts_v1alpha1_axonopsalertroute.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
