## Append samples of your project ##
resources:
- core_v1alpha1_axonopsserver.yaml
- alerts_v1alpha1_axonopsmetricalert.yaml
- alerts_v1alpha1_axonopsalertroute.yaml
- kafka_v1alpha1_axonopshealthcheckhttp.yaml
- kafka_v1alpha1_axonopshealthcheckshell.yaml
- kafka_v1alpha1_axonopshealthchecktcp.yaml
- alerts_v1alpha1_axonopshealthcheckhttp.yaml
- alerts_v1alpha1_axonopshealthcheckshell.yaml
- alerts_v1alpha1_axonopshealthchecktcp.yaml
- alerts_v1alpha1_axonopsalertendpoint.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
