## Append samples of your project ##
resources:
- core_v1alpha1_axonopsserver.yaml
- alerts_v1alpha1_axonopsmetricalert.yaml
- alerts_v1alpha1_axonopsalertroute.yaml
- kafka_v1alpha1_axonopshealthcheckhttp.yaml
- kafka_v1alpha1_axonopshealthcheckshell.yaml
- kafka_v1alpha1_axonopshealthchecktcp.yaml
- alerts_v1alpha1_axonopshealthcheckhttp.yaml
- alerts_v1alpha1_axonopshealthcheckshell.yaml
- alerts_v1alpha1_axonopshealthchecktcp.yaml
- alerts_v1alpha1_axonopsalertendpoint.yaml
- alerts_v1alpha1_axonopsadaptiverepair.yaml
- backups_v1alpha1_axonopsbackup.yaml
- alerts_v1alpha1_axonopsscheduledrepair.yaml
- kafka_v1alpha1_axonopskafkatopic.yaml
- kafka_v1alpha1_axonopskafkaacl.yaml
- kafka_v1alpha1_axonopskafkaconnector.yaml
- alerts_v1alpha1_axonopsdashboardtemplate.yaml
- alerts_v1alpha1_axonopscommitlogarchive.yaml
- alerts_v1alpha1_axonopssilencewindow.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
