//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonAuthentication) DeepCopyInto(out *AxonAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonAuthentication.
func (in *AxonAuthentication) DeepCopy() *AxonAuthentication {
	if in == nil {
		return nil
	}
	out := new(AxonAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonBaseComponent) DeepCopyInto(out *AxonBaseComponent) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.External.DeepCopyInto(&out.External)
	out.Authentication = in.Authentication
	out.Repository = in.Repository
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StorageConfig.DeepCopyInto(&out.StorageConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonBaseComponent.
func (in *AxonBaseComponent) DeepCopy() *AxonBaseComponent {
	if in == nil {
		return nil
	}
	out := new(AxonBaseComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonDashboardComponent) DeepCopyInto(out *AxonDashboardComponent) {
	*out = *in
	in.AxonBaseComponent.DeepCopyInto(&out.AxonBaseComponent)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Gateway.DeepCopyInto(&out.Gateway)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonDashboardComponent.
func (in *AxonDashboardComponent) DeepCopy() *AxonDashboardComponent {
	if in == nil {
		return nil
	}
	out := new(AxonDashboardComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonDbComponent) DeepCopyInto(out *AxonDbComponent) {
	*out = *in
	in.AxonBaseComponent.DeepCopyInto(&out.AxonBaseComponent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonDbComponent.
func (in *AxonDbComponent) DeepCopy() *AxonDbComponent {
	if in == nil {
		return nil
	}
	out := new(AxonDbComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonExternalConfig) DeepCopyInto(out *AxonExternalConfig) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonExternalConfig.
func (in *AxonExternalConfig) DeepCopy() *AxonExternalConfig {
	if in == nil {
		return nil
	}
	out := new(AxonExternalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsConnection) DeepCopyInto(out *AxonOpsConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsConnection.
func (in *AxonOpsConnection) DeepCopy() *AxonOpsConnection {
	if in == nil {
		return nil
	}
	out := new(AxonOpsConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsConnectionList) DeepCopyInto(out *AxonOpsConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsConnectionList.
func (in *AxonOpsConnectionList) DeepCopy() *AxonOpsConnectionList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsConnectionSpec) DeepCopyInto(out *AxonOpsConnectionSpec) {
	*out = *in
	out.APIKeyRef = in.APIKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsConnectionSpec.
func (in *AxonOpsConnectionSpec) DeepCopy() *AxonOpsConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsConnectionStatus) DeepCopyInto(out *AxonOpsConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastValidationTime != nil {
		in, out := &in.LastValidationTime, &out.LastValidationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsConnectionStatus.
func (in *AxonOpsConnectionStatus) DeepCopy() *AxonOpsConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsSecretKeyRef) DeepCopyInto(out *AxonOpsSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsSecretKeyRef.
func (in *AxonOpsSecretKeyRef) DeepCopy() *AxonOpsSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(AxonOpsSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsServer) DeepCopyInto(out *AxonOpsServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsServer.
func (in *AxonOpsServer) DeepCopy() *AxonOpsServer {
	if in == nil {
		return nil
	}
	out := new(AxonOpsServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsServerList) DeepCopyInto(out *AxonOpsServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AxonOpsServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsServerList.
func (in *AxonOpsServerList) DeepCopy() *AxonOpsServerList {
	if in == nil {
		return nil
	}
	out := new(AxonOpsServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AxonOpsServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsServerSpec) DeepCopyInto(out *AxonOpsServerSpec) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(AxonServerComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeSeries != nil {
		in, out := &in.TimeSeries, &out.TimeSeries
		*out = new(AxonDbComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(AxonDbComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Dashboard != nil {
		in, out := &in.Dashboard, &out.Dashboard
		*out = new(AxonDashboardComponent)
		(*in).DeepCopyInto(*out)
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsServerSpec.
func (in *AxonOpsServerSpec) DeepCopy() *AxonOpsServerSpec {
	if in == nil {
		return nil
	}
	out := new(AxonOpsServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsServerStatus) DeepCopyInto(out *AxonOpsServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsServerStatus.
func (in *AxonOpsServerStatus) DeepCopy() *AxonOpsServerStatus {
	if in == nil {
		return nil
	}
	out := new(AxonOpsServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonOpsTLSConfig) DeepCopyInto(out *AxonOpsTLSConfig) {
	*out = *in
	out.Issuer = in.Issuer
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonOpsTLSConfig.
func (in *AxonOpsTLSConfig) DeepCopy() *AxonOpsTLSConfig {
	if in == nil {
		return nil
	}
	out := new(AxonOpsTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonRepository) DeepCopyInto(out *AxonRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonRepository.
func (in *AxonRepository) DeepCopy() *AxonRepository {
	if in == nil {
		return nil
	}
	out := new(AxonRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonServerComponent) DeepCopyInto(out *AxonServerComponent) {
	*out = *in
	in.AxonBaseComponent.DeepCopyInto(&out.AxonBaseComponent)
	out.License = in.License
	in.AgentIngress.DeepCopyInto(&out.AgentIngress)
	in.ApiIngress.DeepCopyInto(&out.ApiIngress)
	in.AgentGateway.DeepCopyInto(&out.AgentGateway)
	in.ApiGateway.DeepCopyInto(&out.ApiGateway)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonServerComponent.
func (in *AxonServerComponent) DeepCopy() *AxonServerComponent {
	if in == nil {
		return nil
	}
	out := new(AxonServerComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AxonTLSConfig) DeepCopyInto(out *AxonTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AxonTLSConfig.
func (in *AxonTLSConfig) DeepCopy() *AxonTLSConfig {
	if in == nil {
		return nil
	}
	out := new(AxonTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerConfig) DeepCopyInto(out *IssuerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerConfig.
func (in *IssuerConfig) DeepCopy() *IssuerConfig {
	if in == nil {
		return nil
	}
	out := new(IssuerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *License) DeepCopyInto(out *License) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new License.
func (in *License) DeepCopy() *License {
	if in == nil {
		return nil
	}
	out := new(License)
	in.DeepCopyInto(out)
	return out
}
