apiVersion: core.axonops.com/v1alpha1
kind: AxonOpsServer
metadata:
  name: serg
  namespace: default
spec:
  server:
    orgName: "axonops"
    repository:
      image: europe-docker.pkg.dev/axonops-public/axonops-docker-dev/axon-server
      tag: 2.0.27-asb4338searchdbtlscacert-1-arm64

  timeSeries: {}
  search: {}

  dashboard:
    gateway:
      enabled: true
      gatewayClassName: "eg"
      hostname: "dash.127.0.0.1.nip.io"
      port: 443
