apiVersion: core.axonops.com/v1alpha1
kind: AxonOpsServer
metadata:
  name: server
  namespace: default
spec:
  server:
    orgName: "AxonOps"
  timeSeries: {}
  search: {}
  dashboard:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
        - "dash.192.168.1.197.nip.io"
      tls:
        - secretName: server-tls
          hosts:
            - "dash.192.168.1.197.nip.io"

