# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.axonops.com_axonopsservers.yaml
- bases/core.axonops.com_axonopsconnections.yaml
- bases/alerts.axonops.com_axonopsmetricalerts.yaml
- bases/alerts.axonops.com_axonopslogalerts.yaml
- bases/alerts.axonops.com_axonopsalertroutes.yaml
- bases/alerts.axonops.com_axonopshealthcheckhttps.yaml
- bases/alerts.axonops.com_axonopshealthcheckshells.yaml
- bases/alerts.axonops.com_axonopshealthchecktcps.yaml
- bases/alerts.axonops.com_axonopsalertendpoints.yaml
- bases/alerts.axonops.com_axonopsadaptiverepairs.yaml
- bases/backups.axonops.com_axonopsbackups.yaml
- bases/alerts.axonops.com_axonopsscheduledrepairs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
