name: E2E Tests

on:
  pull_request:

jobs:
  test-e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create Kube cluster to test against
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: test/e2e/terraform
          command: "apply"
          arg-lock: true
          arg-auto-approve: true
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          arg-var: "exoscale_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Destroy Kube cluster
        if: always()
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: test/e2e/terraform
          command: "destroy"
          arg-lock: true
          arg-auto-approve: true
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          arg-var: "exoscale_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
