name: E2E Tests

on:
  pull_request:

jobs:
  test-e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create Kube cluster to test against
        working-directory: test/e2e/terraform
        run: |
          terraform init
          terraform apply -auto-approve -lock=true \
            -var="exoscale_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Destroy Kube cluster
        if: always()
        working-directory: test/e2e/terraform
        run: |
          terraform destroy -auto-approve -lock=true \
            -var="exoscale_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
