{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "axonops-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "axonops-operator.resourceName" (dict "suffix" "alerts-axonopshealthchecktcp-editor-role" "context" $) }}
rules:
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopshealthchecktcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopshealthchecktcps/status
  verbs:
  - get
{{- end }}
