apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "axonops-operator.resourceName" (dict "suffix" "manager-role" "context" $) }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsadaptiverepairs
  - axonopsalertendpoints
  - axonopsalertroutes
  - axonopscommitlogarchives
  - axonopsdashboardtemplates
  - axonopshealthcheckhttps
  - axonopshealthcheckshells
  - axonopshealthchecktcps
  - axonopslogalerts
  - axonopsmetricalerts
  - axonopsscheduledrepairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsadaptiverepairs/finalizers
  - axonopsalertendpoints/finalizers
  - axonopsalertroutes/finalizers
  - axonopscommitlogarchives/finalizers
  - axonopsdashboardtemplates/finalizers
  - axonopshealthcheckhttps/finalizers
  - axonopshealthcheckshells/finalizers
  - axonopshealthchecktcps/finalizers
  - axonopslogalerts/finalizers
  - axonopsmetricalerts/finalizers
  - axonopsscheduledrepairs/finalizers
  verbs:
  - update
- apiGroups:
  - alerts.axonops.com
  resources:
  - axonopsadaptiverepairs/status
  - axonopsalertendpoints/status
  - axonopsalertroutes/status
  - axonopscommitlogarchives/status
  - axonopsdashboardtemplates/status
  - axonopshealthcheckhttps/status
  - axonopshealthcheckshells/status
  - axonopshealthchecktcps/status
  - axonopslogalerts/status
  - axonopsmetricalerts/status
  - axonopsscheduledrepairs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backups.axonops.com
  resources:
  - axonopsbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backups.axonops.com
  resources:
  - axonopsbackups/finalizers
  verbs:
  - update
- apiGroups:
  - backups.axonops.com
  resources:
  - axonopsbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers/finalizers
  verbs:
  - update
- apiGroups:
  - core.axonops.com
  resources:
  - axonopsservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.axonops.com
  resources:
  - axonopskafkaacls
  - axonopskafkaconnectors
  - axonopskafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.axonops.com
  resources:
  - axonopskafkaacls/finalizers
  - axonopskafkaconnectors/finalizers
  - axonopskafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - kafka.axonops.com
  resources:
  - axonopskafkaacls/status
  - axonopskafkaconnectors/status
  - axonopskafkatopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
